<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\assets\icons\Anywhere.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anywhere.Controls\Anywhere.Controls.csproj" />
    <ProjectReference Include="..\Anywhere.Models\Anywhere.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\icons\Anywhere.ico" LogicalName="Anywhere.Anywhere.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AgentClientProtocol" Version="0.1.5" />
  </ItemGroup>
</Project>
